In [1]:
import torch

In [2]:
t1 = torch.tensor(4.)
t1

tensor(4.)

In [3]:
t1.dtype

torch.float32

In [4]:
t2 = torch.tensor([1., 2, 3, 4])
t2

tensor([1., 2., 3., 4.])

In [5]:
t3 = torch.tensor([[5., 6], [7, 8], [9, 10]])
t3

tensor([[ 5.,  6.],
        [ 7.,  8.],
        [ 9., 10.]])

In [6]:
t4 = torch.tensor([
                [[5., 6, 9], [7, 8, 10]],
                [[9, 10, 12], [12, 56., 86]]])
t4

tensor([[[ 5.,  6.,  9.],
         [ 7.,  8., 10.]],

        [[ 9., 10., 12.],
         [12., 56., 86.]]])

In [7]:
t4.shape

torch.Size([2, 2, 3])

In [8]:
#create tensors
x = torch.tensor(4.)
w = torch.tensor(5., requires_grad = True)
b = torch.tensor(6., requires_grad = True)

In [9]:
y = w * x + b
y

tensor(26., grad_fn=<AddBackward0>)

In [10]:
y.backward()


c:\users\arbaz\anaconda3\envs\cmpt-f726\lib\site-packages\torch\autograd\__init__.py:132: UserWarning: CUDA initialization: Found no NVIDIA driver on your system. Please check that you have an NVIDIA GPU and installed a driver from http://www.nvidia.com/Download/index.aspx (Triggered internally at  ..\c10\cuda\CUDAFunctions.cpp:100.)
  allow_unreachable=True)  # allow_unreachable flag


In [11]:
print(w.grad)

tensor(4.)


In [12]:
import numpy as np
x = np.array([[1, 2], [3, 4.]])
x

array([[1., 2.],
       [3., 4.]])

In [13]:
y = torch.from_numpy(x)
y

tensor([[1., 2.],
        [3., 4.]], dtype=torch.float64)

In [14]:
 x.dtype , y.dtype

(dtype('float64'), torch.float64)

In [15]:
z = y.numpy()
z

array([[1., 2.],
       [3., 4.]])

In [17]:
#pip install jovian
import jovian

<IPython.core.display.Javascript object>

In [18]:
jovian.commit()

<IPython.core.display.Javascript object>

[jovian] Attempting to save notebook..
[jovian] Please enter your API key ( from https://jovian.ai/ ):
API KEY: ········
[jovian] Uploading notebook..
[jovian] Capturing environment..
[jovian] Committed successfully! https://jovian.ai/arbaza/torch


'https://jovian.ai/arbaza/torch'

In [19]:
inputs = np.array([[73, 67, 43], 
                   [91, 88, 64], 
                   [87, 134, 58], 
                   [102, 43, 37], 
                   [69, 96, 70]], dtype='float32')

In [20]:
targets = np.array([[56, 70], 
                    [81, 101], 
                    [119, 133], 
                    [22, 37], 
                    [103, 119]], dtype='float32')

In [24]:
targets

array([[ 56.,  70.],
       [ 81., 101.],
       [119., 133.],
       [ 22.,  37.],
       [103., 119.]], dtype=float32)

In [25]:
# Convert inputs and targets to tensors
inputs = torch.from_numpy(inputs)
targets = torch.from_numpy(targets)
print(inputs)
print(targets)

tensor([[ 73.,  67.,  43.],
        [ 91.,  88.,  64.],
        [ 87., 134.,  58.],
        [102.,  43.,  37.],
        [ 69.,  96.,  70.]])
tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.]])


In [26]:
# Weights and biases
w = torch.randn(2, 3, requires_grad=True)
b = torch.randn(2, requires_grad=True)
print(w)
print(b)

tensor([[-0.6473, -0.5012,  1.7020],
        [ 1.0089, -2.4548,  0.9955]], requires_grad=True)
tensor([-1.3647,  1.2240], requires_grad=True)


In [27]:
def model(x):
    return x @ w.t() + b

In [28]:
# Generate predictions
preds = model(inputs)
print(preds)

tensor([[  -9.0132,  -46.7947],
        [   4.5519,  -59.2807],
        [ -26.1252, -182.2096],
        [ -25.9691,   35.4041],
        [  24.9956,  -95.1409]], grad_fn=<AddBackward0>)


In [29]:
# Compare with targets
print(targets)

tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.]])


In [34]:
diff = targets - preds
torch.sum(diff * diff) / diff.numel()

tensor(22406.4941, grad_fn=<DivBackward0>)

In [35]:
# MSE loss
def mse(t1, t2):
    diff = t1 - t2
    return torch.sum(diff * diff) / diff.numel()

In [36]:
# Compute loss
loss = mse(preds, targets)
print(loss)

tensor(22406.4941, grad_fn=<DivBackward0>)


In [37]:
loss.backward()

In [38]:
print(w)
print(w.grad)

tensor([[-0.6473, -0.5012,  1.7020],
        [ 1.0089, -2.4548,  0.9955]], requires_grad=True)
tensor([[ -6920.7568,  -8016.2373,  -4668.1348],
        [-13094.6582, -16958.8359,  -9722.2402]])


In [39]:
print(b)
print(b.grad)

tensor([-1.3647,  1.2240], requires_grad=True)
tensor([ -82.5120, -161.6044])


In [40]:
w.grad.zero_()
b.grad.zero_()
print(w.grad)
print(b.grad)

tensor([[0., 0., 0.],
        [0., 0., 0.]])
tensor([0., 0.])


In [41]:
# Generate predictions
preds = model(inputs)
print(preds)

tensor([[  -9.0132,  -46.7947],
        [   4.5519,  -59.2807],
        [ -26.1252, -182.2096],
        [ -25.9691,   35.4041],
        [  24.9956,  -95.1409]], grad_fn=<AddBackward0>)


In [42]:
# Calculate the loss
loss = mse(preds, targets)
print(loss)

tensor(22406.4941, grad_fn=<DivBackward0>)


In [43]:
# Compute gradients
loss.backward()
print(w.grad)
print(b.grad)

tensor([[ -6920.7568,  -8016.2373,  -4668.1348],
        [-13094.6582, -16958.8359,  -9722.2402]])
tensor([ -82.5120, -161.6044])


In [44]:
# Adjust weights & reset gradients
with torch.no_grad():
    w -= w.grad * 1e-5
    b -= b.grad * 1e-5
    w.grad.zero_()
    b.grad.zero_()

In [45]:
print(w)
print(b)

tensor([[-0.5781, -0.4210,  1.7487],
        [ 1.1398, -2.2852,  1.0927]], requires_grad=True)
tensor([-1.3639,  1.2256], requires_grad=True)


In [46]:
# Calculate loss
preds = model(inputs)
loss = mse(preds, targets)
print(loss)

tensor(16142.9395, grad_fn=<DivBackward0>)


In [55]:
# Train for 100 epochs
for i in range(100):
    preds = model(inputs)
    loss = mse(preds, targets)
    loss.backward()
    with torch.no_grad():
        w -= w.grad * 1e-5
        b -= b.grad * 1e-5
        w.grad.zero_()
        b.grad.zero_()

In [56]:
# Calculate loss
preds = model(inputs)
loss = mse(preds, targets)
print(loss)

tensor(220.0629, grad_fn=<DivBackward0>)


In [57]:
preds

tensor([[ 56.9781,  74.8684],
        [ 90.9434, 109.5702],
        [ 99.1201, 105.3910],
        [ 22.2135,  62.9157],
        [116.1894, 119.7469]], grad_fn=<AddBackward0>)

In [58]:
targets

tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.]])

In [59]:
jovian.commit()

<IPython.core.display.Javascript object>

[jovian] Attempting to save notebook..
[jovian] Updating notebook "arbaza/torch" on https://jovian.ai/
[jovian] Uploading notebook..
[jovian] Capturing environment..
[jovian] Committed successfully! https://jovian.ai/arbaza/torch


'https://jovian.ai/arbaza/torch'

In [60]:
import torch.nn as nn

In [61]:
# Input (temp, rainfall, humidity)
inputs = np.array([[73, 67, 43], [91, 88, 64], [87, 134, 58], 
                   [102, 43, 37], [69, 96, 70], [73, 67, 43], 
                   [91, 88, 64], [87, 134, 58], [102, 43, 37], 
                   [69, 96, 70], [73, 67, 43], [91, 88, 64], 
                   [87, 134, 58], [102, 43, 37], [69, 96, 70]], 
                  dtype='float32')

# Targets (apples, oranges)
targets = np.array([[56, 70], [81, 101], [119, 133], 
                    [22, 37], [103, 119], [56, 70], 
                    [81, 101], [119, 133], [22, 37], 
                    [103, 119], [56, 70], [81, 101], 
                    [119, 133], [22, 37], [103, 119]], 
                   dtype='float32')

inputs = torch.from_numpy(inputs)
targets = torch.from_numpy(targets)

In [62]:
from torch.utils.data import TensorDataset

In [63]:
# Define dataset
train_ds = TensorDataset(inputs, targets)
train_ds[0:3]

(tensor([[ 73.,  67.,  43.],
         [ 91.,  88.,  64.],
         [ 87., 134.,  58.]]),
 tensor([[ 56.,  70.],
         [ 81., 101.],
         [119., 133.]]))

In [64]:
from torch.utils.data import DataLoader

In [65]:
# Define data loader
batch_size = 5
train_dl = DataLoader(train_ds, batch_size, shuffle=True)

In [66]:
for xb, yb in train_dl:
    print(xb)
    print(yb)
    break

tensor([[102.,  43.,  37.],
        [ 73.,  67.,  43.],
        [ 87., 134.,  58.],
        [ 69.,  96.,  70.],
        [102.,  43.,  37.]])
tensor([[ 22.,  37.],
        [ 56.,  70.],
        [119., 133.],
        [103., 119.],
        [ 22.,  37.]])


In [67]:
# Define model
model = nn.Linear(3, 2)
print(model.weight)
print(model.bias)

Parameter containing:
tensor([[ 0.5271, -0.4058,  0.4650],
        [ 0.4888, -0.3717,  0.4135]], requires_grad=True)
Parameter containing:
tensor([0.2770, 0.0604], requires_grad=True)


In [68]:
# Parameters
list(model.parameters())

[Parameter containing:
 tensor([[ 0.5271, -0.4058,  0.4650],
         [ 0.4888, -0.3717,  0.4135]], requires_grad=True),
 Parameter containing:
 tensor([0.2770, 0.0604], requires_grad=True)]

In [69]:
# Generate predictions
preds = model(inputs)
preds

tensor([[31.5658, 28.6151],
        [42.2983, 38.2899],
        [18.7340, 16.7558],
        [53.8005, 49.2290],
        [30.2457, 27.0445],
        [31.5658, 28.6151],
        [42.2983, 38.2899],
        [18.7340, 16.7558],
        [53.8005, 49.2290],
        [30.2457, 27.0445],
        [31.5658, 28.6151],
        [42.2983, 38.2899],
        [18.7340, 16.7558],
        [53.8005, 49.2290],
        [30.2457, 27.0445]], grad_fn=<AddmmBackward>)

In [70]:
# Import nn.functional
import torch.nn.functional as F

In [71]:
# Define loss function
loss_fn = F.mse_loss

In [72]:
loss = loss_fn(model(inputs), targets)
print(loss)

tensor(4621.5918, grad_fn=<MseLossBackward>)


In [73]:
# Define optimizer
opt = torch.optim.SGD(model.parameters(), lr=1e-5)

In [74]:
# Utility function to train the model
def fit(num_epochs, model, loss_fn, opt):
    
    # Repeat for given number of epochs
    for epoch in range(num_epochs):
        
        # Train with batches of data
        for xb,yb in train_dl:
            
            # 1. Generate predictions
            pred = model(xb)
            
            # 2. Calculate loss
            loss = loss_fn(pred, yb)
            
            # 3. Compute gradients
            loss.backward()
            
            # 4. Update parameters using gradients
            opt.step()
            
            # 5. Reset the gradients to zero
            opt.zero_grad()
        
        # Print the progress
        if (epoch+1) % 10 == 0:
            print('Epoch [{}/{}], Loss: {:.4f}'.format(epoch+1, num_epochs, loss.item()))

In [75]:
fit(100, model, loss_fn, opt)

Epoch [10/100], Loss: 1630.2518
Epoch [20/100], Loss: 639.8240
Epoch [30/100], Loss: 723.1171
Epoch [40/100], Loss: 324.9940
Epoch [50/100], Loss: 205.9380
Epoch [60/100], Loss: 230.0423
Epoch [70/100], Loss: 40.1082
Epoch [80/100], Loss: 57.6481
Epoch [90/100], Loss: 41.5383
Epoch [100/100], Loss: 47.7761


In [76]:
# Generate predictions
preds = model(inputs)
preds

tensor([[ 58.9800,  72.0114],
        [ 83.8091, 100.7836],
        [112.3812, 129.7706],
        [ 31.2056,  46.9028],
        [ 98.8353, 113.5905],
        [ 58.9800,  72.0114],
        [ 83.8091, 100.7836],
        [112.3812, 129.7706],
        [ 31.2056,  46.9028],
        [ 98.8353, 113.5905],
        [ 58.9800,  72.0114],
        [ 83.8091, 100.7836],
        [112.3812, 129.7706],
        [ 31.2056,  46.9028],
        [ 98.8353, 113.5905]], grad_fn=<AddmmBackward>)

In [77]:
targets

tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.],
        [ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.],
        [ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.]])

In [ ]:
jovian.commit()

<IPython.core.display.Javascript object>

[jovian] Attempting to save notebook..
